#!/bin/sh
pgrep >/dev/null headless_shell && exit
echo starting headless_shell
mkdir -p /tmp/data-path
mkdir -p /tmp/cache-dir
./headless_shell \
  --disable-gpu \
  --no-sandbox \
  --homedir=/tmp \
  --single-process \
  --data-path=/tmp/data-path \
  --disk-cache-dir=/tmp/cache-dir \
  --remote-debugging-port=9222 \
&
